import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "./components/theme-provider";
import NavBar from "./components/NavBar";
import { Footer } from "./components/Footer";

const poppins = Poppins({ 
  weight:'500', subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} antialiased`}
      >
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <NavBar/>
       <main className="max-w-6xl mx-auto px-4 justify-center items-center">{children}
       <Footer/>
       </main> 
       
        </ThemeProvider>
      </body>
    </html>
  );
}
